services:
  # ----------------------------------------
  # 1. Backend (Go API)
  # ----------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shiptrack_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - APP_ENV=production
      - POSTGRES_DSN=${POSTGRES_DSN}
      - REDIS_ADDR=${REDIS_ADDR}
      - BINDERBYTE_URL=${BINDERBYTE_URL}
      - BINDERBYTE_API_KEY=${BINDERBYTE_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}

  # ----------------------------------------
  # 2. Frontend (Vue + Nginx)
  # ----------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shiptrack_frontend
    restart: unless-stopped
    ports:
      - "3006:3006"
    depends_on:
      - backend

# Hubungkan ke network eksternal
networks:
  default:
    name: postgres_net
    external: true
